CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES ('USER'), ('ADMIN');

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE CHECK (email = lower(email)),
    password VARCHAR(60) NOT NULL,
    name VARCHAR(50),
    phone VARCHAR(20),
    balance NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
    avatar_url VARCHAR(255),
    active BOOLEAN NOT NULL,
    blocked BOOLEAN NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CHECK (deleted_at IS NOT NULL OR (email IS NOT NULL AND name IS NOT NULL)),
    CHECK (deleted_at IS NULL OR active = false)
);
