CREATE TABLE verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    code_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    target_value VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code_type VARCHAR(30) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    UNIQUE (user_id, code_type)
);
