CREATE TABLE addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(150) NOT NULL,
    house VARCHAR(20) NOT NULL,
    apartment VARCHAR(20),
    postal_code VARCHAR(6) CHECK (postal_code ~ '^[0-9]{6}$'),
    comment VARCHAR(255),
    selected BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_addresses_user_id ON addresses (user_id);

CREATE UNIQUE INDEX uq_addresses_user_selected ON addresses (user_id) WHERE selected;
